# Generated by Django 4.2.1 on 2023-11-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_cars_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
    ]
